### PR TITLE
vayu: separate builds for huaxing and tianma panels

### PR DESCRIPTION
**Pull request by bibarub**
### Description

making separate configurations for two different panels on one device to simplify building 

### Checklist

* [x] Have you tested the change you are submitting?
* [x] Is the commits history nice and clean?

### CODE REVIEW

**Comment by bibarub** [comment]
tested.

**Comment by halal-beef** [comment]
did it work

**Review by halal-beef — CHANGES_REQUESTED** [review]
you may need to change the ci for the devices now

**Comment by qaz6750** [comment]
# Can you find a way for GPU drivers/others to choose the appropriate panel?

**Review by qaz6750 — COMMENTED** [review]
* Fix Ci based on changes

**Comment by bibarub** [comment]
> * Fix Ci based on changes

should be done

**Review by qaz6750 — APPROVED** [review]

**Pull request merged**
