### PR TITLE
Update it

### PR DESCRIPTION
**Pull request by ETCHDEV**
### Description

[Description of the changes you are submitting]

### Checklist

* [ ] Have you tested the change you are submitting?
* [ ] Is the commits history nice and clean?

### CODE REVIEW

**Comment by gus33000** [comment]
Edk2 main branch is known to introduce breaking changes often breaking the build process. As a result if you drop the last commit here you may one day make builds fail due to an update on their end. I think it would be better to set the last known good commit sha1 instead of removing it all together. Even if you can rely on git submodule functionality it at least documents nicely the commit intended to work

**Comment by gus33000** [comment]
@ETCHDEV whats the point of this PR? I have not gotten an answer on this and it looks like you made a change 2 days ago. Should we close this? You do not seem open to discussing https://github.com/edk2-porting/edk2-msm/pull/386#issuecomment-2074646627 or make changes

**Comment by ETCHDEV** [comment]
Sorry for late reply, but ya I am closing the commit has this commit does nothing

**Comment by n00b69** [comment]
@ETCHDEV Poor lisa

**Comment by ETCHDEV** [comment]
Btw you can tell in grp that lisa is sold now. So no, not returning to woa on lisa

**Comment by TAOcroatia** [comment]
@gus33000 Gus? Renegade? What?

**Pull request closed without merging**
