### PR TITLE
Delete qcom's shit and add powerful, gaming mt6577

### PR DESCRIPTION
**Pull request by govnoed1488dorogayayakupiltebehuinu911**
### Description

[Description of the changes you are submitting]

### Checklist

* [N] Have you tested the change you are submitting?
* [idk] Is the commits history nice and clean?

### CODE REVIEW

**Comment by BigfootACA** [comment]
this repo only accepts qualcomm related content.
meaning of edk2-msm name:
- edk2: Tianocore EDK II: EFI Development Kit
- msm: Qualcomm MSM (Snapdragon): Mobile Station Modem

**Comment by govnoed1488dorogayayakupiltebehuinu911** [comment]
> this repo only accepts qualcomm related content. meaning of edk2-msm name:
> 
> * edk2: Tianocore EDK II: EFI Development Kit
> * msm: Qualcomm MSM (Snapdragon): Mobile Station Modem

fuck you

**Comment by halal-beef** [comment]
@govnoed1488dorogayayakupiltebehuinu911 so real, when exynos bringup

**Comment by BigfootACA** [comment]
> > this repo only accepts qualcomm related content. meaning of edk2-msm name:
> > 
> > * edk2: Tianocore EDK II: EFI Development Kit
> > * msm: Qualcomm MSM (Snapdragon): Mobile Station Modem
> 
> fuck you

nice fuck, good bye

**Pull request closed without merging**
