### PR TITLE
Initial support for lisa

### PR DESCRIPTION
**Pull request by ETCHDEV**
Added files to support Mi 11 Lite NE 5G. Took some files from mona as those have similar hardware

### CODE REVIEW

**Comment by qaz6750** [comment]
Thank you for your efforts. You need to wait for a while

**Comment by qaz6750** [comment]
From my personal point of view, you can sort out your submissions and combine some into one

**Comment by ETCHDEV** [comment]
OK, BTW I am not going to maintain this device frequently until April where I have plenty of time. Also working on CEMU to android project

**Comment by strongtz** [comment]
Please follow upstream changes by renaming DSDT.AML to DSDT.aml

**Pull request merged**
