### PR TITLE
sm8250 windows pe support and j716f update

### PR DESCRIPTION
**Pull request by cloudsweets**
(beta)

### CODE REVIEW

**Comment by qaz6750** [comment]
image
These should be submitted to https://github.com/edk2-porting/edk2-sdm845-binary

**Review by qaz6750 — APPROVED** [review]

**Comment by cloudsweets** [comment]
> 영상
> https://github.com/edk2-porting/edk2-sdm845-binary 에 제출해야 합니다.

Change done

**Comment by strongtz** [comment]
Why did you remove Dsdt.asl? And where does the IORT table etc. even come from? sm7325 acpi tables won't work here.

**Comment by cloudsweets** [comment]
> 왜 Dsdt.asl을 제거했습니까? 그리고 IORT 테이블 등은 어디에서 왔습니까? sm7325 acpi 테이블은 여기에서 작동하지 않습니다.

I'll fix it right away

**Comment by cloudsweets** [comment]
> Why did you remove Dsdt.asl? And where does the IORT table etc. even come from? sm7325 acpi tables won't work here.

I'll fix it right away

**Pull request closed without merging**
