### PR TITLE
OnePlus: Add support for OnePlus 7 pro (guacamole)

### PR DESCRIPTION
**Pull request by silime**
### Description

[Description of the changes you are submitting]

### Checklist

* [ ] Have you tested the change you are submitting?
* [ ] Is the commits history nice and clean?

### CODE REVIEW

**Comment by TheMorc** [comment]
Nice! Does this have working buttons?

**Comment by silime** [comment]
No, Buttons only works in SimpleInit，under Windows boot manager Buttons was broken，I Don`t why？🥲

**Comment by TheMorc** [comment]
> No, Buttons only works in SimpleInit，under Windows boot manager Buttons was broken，I Don`t why？🥲

oh, so it's same as for me on my hotdog

**Comment by TheMorc** [comment]
@silime one question, did you try USB?

**Comment by silime** [comment]
No, I just bought the hub yesterday😆

**Comment by TheMorc** [comment]
@silime question, are you on Telegram or Discord? I can't seem to find you...

**Pull request merged**
